#!/usr/bin/env python3
"""
report.py — генерация отчёта
Fixes:
  - Не теряет события молча (показывает сколько обрезано)
  - Бэкап предыдущего отчёта (не перезаписывает)
  - Читает scoring breakdown из severity.txt
  - Добавляет статистику из event_counts.txt
"""
import os
import shutil
from datetime import datetime

BASE_DIR     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_EVENTS   = os.path.join(BASE_DIR, "output", "events.txt")
OUT_IOC      = os.path.join(BASE_DIR, "output", "iocs.txt")
OUT_SEVERITY = os.path.join(BASE_DIR, "output", "severity.txt")
OUT_COUNTS   = os.path.join(BASE_DIR, "output", "event_counts.txt")
OUT_REPORT   = os.path.join(BASE_DIR, "output", "final_report.txt")
ARCHIVE_DIR  = os.path.join(BASE_DIR, "output", "archive")

# --- Бэкап предыдущего отчёта ---
if os.path.exists(OUT_REPORT):
    os.makedirs(ARCHIVE_DIR, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    shutil.copy(OUT_REPORT, os.path.join(ARCHIVE_DIR, f"final_report_{ts}.txt"))
    print(f"    Предыдущий отчёт сохранён в output/archive/")

with open(OUT_EVENTS,   encoding="utf-8") as f: events_raw   = f.read()
with open(OUT_IOC,      encoding="utf-8") as f: iocs         = f.read()
with open(OUT_SEVERITY, encoding="utf-8") as f: severity_raw = f.read()
with open(OUT_COUNTS,   encoding="utf-8") as f: counts       = f.read()

severity_level = severity_raw.splitlines()[0].strip()

# --- Показываем события, честно обрезаем ---
MAX_CHARS   = 3000
events_show = events_raw[:MAX_CHARS]
total_chars = len(events_raw)
truncated   = total_chars > MAX_CHARS
trunc_note  = (
    f"\n... [Показано {MAX_CHARS} из {total_chars} символов. "
    f"Полный список: output/events.txt]\n"
    if truncated else ""
)

report = f"""
{'='*60}
         SOC INCIDENT TRIAGE REPORT
{'='*60}
Date     : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Severity : {severity_level}

DISCLAIMER:
This report is generated by a keyword-based tool.
It is NOT a substitute for manual analyst review.
False positives and false negatives are possible.

{'='*60}
INDICATORS OF COMPROMISE
{'='*60}
{iocs}

{'='*60}
TOP REPEATED EVENTS
{'='*60}
{counts}

{'='*60}
KEY EVENTS (sample)
{'='*60}
{events_show}{trunc_note}

{'='*60}
SEVERITY SCORING
{'='*60}
{severity_raw}

{'='*60}
RECOMMENDATIONS
{'='*60}
1. Investigate source IPs — check geo, reputation (VirusTotal, AbuseIPDB)
2. Check listed user accounts for compromise
3. Review full events.txt for false positives
4. If HIGH: consider blocking IPs, resetting credentials, escalating

MITRE ATT&CK:
  T1110 — Brute Force
  T1078 — Valid Accounts
  T1021 — Remote Services
{'='*60}
"""

with open(OUT_REPORT, "w", encoding="utf-8") as f:
    f.write(report)

print(f"[+] Report generated → output/final_report.txt")
if truncated:
    print(f"    [!] Events обрезаны: показано {MAX_CHARS} из {total_chars} символов")
